# Site settings
title: Your Name - Researcher
email: email@example.com
description: >-
  Personal website of [Your Name], a researcher in [Your Field].
  Showcasing research projects, publications, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yourusername
github_username:  yourusername
linkedin_username: yourusername
google_scholar_id: yourid
orcid_id: your-orcid-id

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  
# Custom settings
show_downloads: false
google_analytics: # Your Google Analytics tracking ID